name: News Scraper

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜 12 點運行（UTC 時間）
  workflow_dispatch: # 允許手動觸發

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run the web scraper
      run: |
        python scraper.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add news_data.json
        git commit -m 'Update news data'
        git push
